name: Build
on:
  push:
    branches:
      - master
    paths:
      - "src/**"
      - "package.json"
      - ".github/workflows/build.yml"

jobs:
  build:
    name: Build compiled JS version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm run build

      - name: Compile TypeScript into compressed JavaScript
        run: npm run build
